version: 2

project_name: go-wordle

builds:
  - id: backend
    dir: ./backend
    main: ./server
    binary: go-wordle-server
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

  - id: tui
    dir: ./tui
    main: .
    binary: go-wordle
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: backend
    ids:
      - backend
    formats:
      - tar.gz

  - id: tui
    ids:
      - tui
    formats:
      - tar.gz
      - zip

checksum:
  name_template: checksums.txt

snapshot:
  version_template: "{{ incpatch .Version }}-snapshot"

changelog:
  use: git
  sort: asc

scoop:
  bucket:
    owner: RaphaelAZ
    name: scoop-bucket-gowordle
  folder: bucket
  commit_author:
    name: RaphaelAz
    email: azevedo.raphael2017@gmail.com
  commit_msg_template: "Scoop update for {{ .ProjectName }} version {{ .Version }}"
  description: "Gowordle - CLI Wordle game"
  homepage: "https://github.com/RaphaelAZ/go-wordle"
  license: MIT